name: asl
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.10
    - numpy
    - opencv-python
    - matplotlib
    - pip
    - notebook
    - pip:
          - mediapipe
          - scikit-learn
